version: "3.9"
services:
  mysql:
    image: mysql
    volumes:
      - ./mysql_data:/var/lib/mysql_data
    env_file:
      - .env
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: rootP@ssw0rd
      MYSQL_DATABASE: ${DB_DATABASE}
  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
    ports:
      - 8800:80
